export default [
  // {value: 'Free legal consultation of lawyers, lawyers', label: 'Free legal consultation of lawyers, lawyers'},
  // {value:'Free legal consultation of lawyers, lawyers in administrative cases',label:'Free legal consultation of lawyers, lawyers in administrative cases'},
  // {value:'Free legal consultation of lawyers, lawyers for the deprivation of a driver’s license',label:'Free legal consultation of lawyers, lawyers for the deprivation of a driver’s license'},
  // {value:'Legal advice on car lawyer services',label:'Legal advice on car lawyer services'},
  // {value:'Legal representation by a lawyer for deprivation of rights in the traffic police',label:'Legal representation by a lawyer for deprivation of rights in the traffic police'},
  // {value:'Legal assistance of lawyers',label:'Legal assistance of lawyers'},
  // {value:'Administrative Lawyer Services',label:'Administrative Lawyer Services'},
  // {value:'Services of a credit lawyer',label:'Services of a credit lawyer'},
  // {value:'Legal assistance in compiling a complaint against a judge',label:'Legal assistance in compiling a complaint against a judge'},
  // {value:'Legal assistance in drawing up a statement to the court',label:'Legal assistance in drawing up a statement to the court'},
  // {value:'Legal examination of documents',label:'Legal examination of documents'},
  // {value:'Legal assistance in drawing up a complaint against a judge of the peace',label:'Legal assistance in drawing up a complaint against a judge of the peace'}

  { value: 'Free legal consultation of lawyers, lawyers', label: 'Free legal consultation of lawyers, lawyers'},
  { value: 'Divorce', label: 'Divorce'},
  { value: 'Divorce1', label: 'Divorce1'},
  { value: 'Divorce21', label: 'Divorce21'},
  { value: 'Divorce22', label: 'Divorce22'},
  { value: 'Divorce23', label: 'Divorce23'},
  { value: 'Divorce24', label: 'Divorce24'},
  { value: 'Family_law', label: 'Family law'},
  { value: 'Family_law1', label: 'Family law1'},
  { value: 'Family_law2', label: 'Family law2'},
  { value: 'Child_custody', label: 'Child custody'},
  { value: 'Child_custody1', label: 'Child custody1'},
  { value: 'Child_custody2', label: 'Child custody2'},
  { value: 'Child_custody3', label: 'Child custody3'},
];