export const ref = {
  SAVE_FEE_RETAINER: 'SAVE_FEE_RETAINER',
  SAVE_OCCUPATION: 'SAVE_OCCUPATION',
  SAVE_STATE: 'SAVE_STATE',
  SAVE_LANGUAGE: 'SAVE_LANGUAGE',
  SAVE_PAYMENT: 'SAVE_PAYMENT',
  SAVE_GENDER: 'SAVE_GENDER',
  SAVE_STATUS: 'SAVE_STATUS',
  SAVE_TYPE: 'SAVE_TYPE',
  SAVE_COUNTRY: 'SAVE_COUNTRY',
};

export const user = {
  SAVE_USER_PROFILE: 'SAVE_USER_PROFILE',
  SET_STATE_GET_USER_PROFILE_REQUEST: 'SET_STATE_GET_USER_PROFILE_REQUEST',
  SET_STATE_UPDATE_USER_PROFILE_REQUEST: 'SET_STATE_UPDATE_USER_PROFILE_REQUEST',
  SET_STATE_REGISTER_USER_PROFILE_REQUEST: 'SET_STATE_REGISTER_USER_PROFILE_REQUEST',
  SAVE_NOTIFICATIONS_LIST: 'SAVE_NOTIFICATIONS_LIST',
  READ_NOTIFICATION: 'READ_NOTIFICATION',
  SAVE_FAVORITES_LIST: 'SAVE_FAVORITES_LIST',
  ADD_TO_FAVORITES_LIST: 'ADD_TO_FAVORITES_LIST',
  REMOVE_FROM_FAVORITES_LIST: 'REMOVE_FROM_FAVORITES_LIST',
  CLEAR_USER_STORE: 'CLEAR_USER_STORE'
};

export const lawyer = {
  SAVE_LAWYER_PROFILE: 'SAVE_LAWYER_PROFILE',
  UPDATE_LAWYER_INFO: 'UPDATE_LAWYER_INFO',
  SAVE_LAWYER_FROM_DATABASE: 'SAVE_LAWYER_FROM_DATABASE',
  SET_STATE_GET_LAWYER_PROFILE_REQUEST: 'SET_STATE_GET_LAWYER_PROFILE_REQUEST',
  SET_STATE_UPDATE_LAWYER_PROFILE_REQUEST: 'SET_STATE_UPDATE_LAWYER_PROFILE_REQUEST',

  SAVE_COMPANY: 'SAVE_COMPANY',
  SAVE_SERVICE: 'SAVE_SERVICE',
  SAVE_LICENSE: 'SAVE_LICENSE',

  SAVE_NOTIFICATIONS_LIST: 'SAVE_NOTIFICATIONS_LIST',
  READ_NOTIFICATION: 'READ_NOTIFICATION',
};

export const company = {
  CREATE_COMPANY: 'CREATE_COMPANY',
};
